language: rust
cache: cargo
sudo: required

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly

os:
  - linux

install:
  - docker pull pmem/pmemkv:ubuntu-18.04

script:
  - ./docker_build.sh
