language: rust
cache: cargo

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly

os:
  - linux

services:
  docker

before_install:
  - docker pull pmem/pmemkv:ubuntu-18.04

script:
  - ./docker_build.sh
