version: 2

aliases:
  - &install_common |
      apt-get update -qq
      apt-get install -qq autoconf automake cmake doxygen gcc g++ libtool libndctl-dev libnuma-dev rapidjson-dev software-properties-common wget
      apt-get install -qq libtbb-dev git pkg-config libdaxctl-dev libjson-c-dev libkmod-dev libncurses5-dev libudev-dev libunwind8-dev numactl

jobs:
  build:
    docker:
      - image: ubuntu:bionic
    steps:
      - run: *install_common
      - run: |
          git clone https://github.com/pmem/pmdk
          cd pmdk
          git checkout 695e6eba28c53a69a0ef7bad3cc0f45c21ef3e00
          make
          make install
          cd ..
      - run: |
          git clone https://github.com/pmem/libpmemobj-cpp
          cd libpmemobj-cpp
          git checkout 8d86c76c81167d9e352158ad87f169f554e5d794
          mkdir build
          cd build
          cmake ..
          make
          make install
          cd ../..
      - run: |
          git clone https://github.com/memkind/memkind
          cd memkind
          git checkout v1.9.0
          ./build.sh
          make install
          cd ..
      - run: |
          git clone https://github.com/pmem/pmemkv
          cd pmemkv
          make
          make install
          cd ..
      - run: |
          wget https://raw.githubusercontent.com/rust-lang/rustup.rs/master/rustup-init.sh
          chmod u+x rustup-init.sh
          ./rustup-init.sh -y
      - run: |
          git clone https://github.com/photoszzt/pmemkv-rs
          cd pmemkv-rs
          $HOME/.cargo/bin/cargo build --verbose --all
          $HOME/.cargo/bin/cargo test --verbose --all
