/* automatically generated by rust-bindgen */

pub type KVAllCallback = ::std::option::Option<
    unsafe extern "C" fn(
        context: *mut ::std::os::raw::c_void,
        keybytes: ::std::os::raw::c_int,
        key: *const ::std::os::raw::c_char,
    ),
>;
pub type KVEachCallback = ::std::option::Option<
    unsafe extern "C" fn(
        context: *mut ::std::os::raw::c_void,
        keybytes: ::std::os::raw::c_int,
        key: *const ::std::os::raw::c_char,
        valuebytes: ::std::os::raw::c_int,
        value: *const ::std::os::raw::c_char,
    ),
>;
pub type KVGetCallback = ::std::option::Option<
    unsafe extern "C" fn(
        context: *mut ::std::os::raw::c_void,
        valuebytes: ::std::os::raw::c_int,
        value: *const ::std::os::raw::c_char,
    ),
>;
pub type KVStartFailureCallback = ::std::option::Option<
    unsafe extern "C" fn(
        context: *mut ::std::os::raw::c_void,
        engine: *const ::std::os::raw::c_char,
        config: *const ::std::os::raw::c_char,
        msg: *const ::std::os::raw::c_char,
    ),
>;
pub type __int8_t = ::std::os::raw::c_schar;
pub type __int32_t = ::std::os::raw::c_int;
pub type __int64_t = ::std::os::raw::c_long;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct KVEngine {
    _unused: [u8; 0],
}
extern "C" {
    pub fn kvengine_start(
        context: *mut ::std::os::raw::c_void,
        engine: *const ::std::os::raw::c_char,
        config: *const ::std::os::raw::c_char,
        callback: KVStartFailureCallback,
    ) -> *mut KVEngine;
}
extern "C" {
    pub fn kvengine_stop(kv: *mut KVEngine);
}
extern "C" {
    pub fn kvengine_all(kv: *mut KVEngine, context: *mut ::std::os::raw::c_void, c: KVAllCallback);
}
extern "C" {
    pub fn kvengine_all_above(
        kv: *mut KVEngine,
        context: *mut ::std::os::raw::c_void,
        kb: i32,
        k: *const ::std::os::raw::c_char,
        c: KVAllCallback,
    );
}
extern "C" {
    pub fn kvengine_all_below(
        kv: *mut KVEngine,
        context: *mut ::std::os::raw::c_void,
        kb: i32,
        k: *const ::std::os::raw::c_char,
        c: KVAllCallback,
    );
}
extern "C" {
    pub fn kvengine_all_between(
        kv: *mut KVEngine,
        context: *mut ::std::os::raw::c_void,
        kb1: i32,
        k1: *const ::std::os::raw::c_char,
        kb2: i32,
        k2: *const ::std::os::raw::c_char,
        c: KVAllCallback,
    );
}
extern "C" {
    pub fn kvengine_count(kv: *mut KVEngine) -> i64;
}
extern "C" {
    pub fn kvengine_count_above(
        kv: *mut KVEngine,
        kb: i32,
        k: *const ::std::os::raw::c_char,
    ) -> i64;
}
extern "C" {
    pub fn kvengine_count_below(
        kv: *mut KVEngine,
        kb: i32,
        k: *const ::std::os::raw::c_char,
    ) -> i64;
}
extern "C" {
    pub fn kvengine_count_between(
        kv: *mut KVEngine,
        kb1: i32,
        k1: *const ::std::os::raw::c_char,
        kb2: i32,
        k2: *const ::std::os::raw::c_char,
    ) -> i64;
}
extern "C" {
    pub fn kvengine_each(
        kv: *mut KVEngine,
        context: *mut ::std::os::raw::c_void,
        c: KVEachCallback,
    );
}
extern "C" {
    pub fn kvengine_each_above(
        kv: *mut KVEngine,
        context: *mut ::std::os::raw::c_void,
        kb: i32,
        k: *const ::std::os::raw::c_char,
        c: KVEachCallback,
    );
}
extern "C" {
    pub fn kvengine_each_below(
        kv: *mut KVEngine,
        context: *mut ::std::os::raw::c_void,
        kb: i32,
        k: *const ::std::os::raw::c_char,
        c: KVEachCallback,
    );
}
extern "C" {
    pub fn kvengine_each_between(
        kv: *mut KVEngine,
        context: *mut ::std::os::raw::c_void,
        kb1: i32,
        k1: *const ::std::os::raw::c_char,
        kb2: i32,
        k2: *const ::std::os::raw::c_char,
        c: KVEachCallback,
    );
}
extern "C" {
    pub fn kvengine_exists(kv: *mut KVEngine, kb: i32, k: *const ::std::os::raw::c_char) -> i8;
}
extern "C" {
    pub fn kvengine_get(
        kv: *mut KVEngine,
        context: *mut ::std::os::raw::c_void,
        kb: i32,
        k: *const ::std::os::raw::c_char,
        c: KVGetCallback,
    );
}
extern "C" {
    pub fn kvengine_get_copy(
        kv: *mut KVEngine,
        kb: i32,
        k: *const ::std::os::raw::c_char,
        maxvaluebytes: i32,
        value: *mut ::std::os::raw::c_char,
    ) -> i8;
}
extern "C" {
    pub fn kvengine_put(
        kv: *mut KVEngine,
        kb: i32,
        k: *const ::std::os::raw::c_char,
        vb: i32,
        v: *const ::std::os::raw::c_char,
    ) -> i8;
}
extern "C" {
    pub fn kvengine_remove(kv: *mut KVEngine, kb: i32, k: *const ::std::os::raw::c_char) -> i8;
}
